name:                servant-presentation
version:             0.1.0.0
github:              "githubuser/servant-presentation"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/servant-presentation#readme>

dependencies:
- base >= 4.7 && < 5
- servant-server
- servant-swagger
- servant-swagger-ui
- servant-js
- wai-middleware-metrics
- ekg
- ekg-core
- monad-metrics
- mtl
- aeson
- wai
- wai-logger
- wai-extra
- http-api-data
- filepath
- warp
- text
- containers >= 0.5.11 && < 0.5.12
- string-conversions
- bytestring
- data-default
- time
- swagger2

library:
  source-dirs: src

executables:
  servant-presentation-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-T
    dependencies:
    - servant-presentation

tests:
  servant-presentation-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - servant-presentation
